#!/usr/bin/env bash
# Fetch prod DATABASE_URL over SSH and write .env.prod.local (localhost tunnel port).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib/vps-ssh.sh
source "$ROOT/scripts/lib/vps-ssh.sh"

LOCAL_PORT="${PROD_DB_LOCAL_PORT:-5433}"
REMOTE_ENV="/opt/humiliation-game/apps/server/.env"
OUT_FILE="$ROOT/.env.prod.local"

line="$("${SSH[@]}" "$VPS_HOST" "grep -E '^DATABASE_URL=' '$REMOTE_ENV' | head -1")"
if [[ -z "$line" ]]; then
  echo "Could not read DATABASE_URL from $VPS_HOST:$REMOTE_ENV" >&2
  exit 1
fi

database_url="$(
  REMOTE_DATABASE_URL_LINE="$line" LOCAL_PORT="$LOCAL_PORT" node <<'NODE'
const localPort = process.env.LOCAL_PORT ?? '5433';
const line = process.env.REMOTE_DATABASE_URL_LINE?.trim() ?? '';
const raw = line.replace(/^DATABASE_URL=/, '').replace(/^"/, '').replace(/"$/, '');
let url;
try {
  url = new URL(raw);
} catch {
  console.error('Invalid DATABASE_URL from server');
  process.exit(1);
}
url.username = decodeURIComponent(url.username);
url.password = decodeURIComponent(url.password);
url.hostname = '127.0.0.1';
url.port = localPort;
process.stdout.write(url.toString());
NODE
)"

cat >"$OUT_FILE" <<EOF
# Generated by scripts/db-prod-env.sh — do not commit.
# Requires: npm run db:prod:tunnel (in another terminal)
DATABASE_URL="${database_url}"
EOF
chmod 600 "$OUT_FILE"

echo "Wrote $OUT_FILE"
echo "Next: npm run db:prod:tunnel   # keep running"
echo "      npm run db:prod:studio   # Prisma Studio on prod data"
